cosmos/web/views.py
import itertools as it
from operator import attrgetter

from flask import Markup, render_template, Blueprint, redirect, url_for, flash, abort, request
from sqlalchemy import desc

from .. import Execution, Stage, Task, TaskStatus
from ..job.JobManager import JobManager
from . import filters
from ..graph.draw import draw_task_graph, draw_stage_graph


def gen_bprint(cosmos_app):
    session = cosmos_app.session

    def get_execution(id):
        return session.query(Execution).filter_by(id=id).one()

    bprint = Blueprint('cosmos', __name__, template_folder='templates', static_folder='static',
                       static_url_path='/cosmos/static')
    filters.add_filters(bprint)

    @bprint.route('/execution/delete/<int:id>')
    def execution_delete(id):
        e = get_execution(id)
        e.delete(delete_files=True)
        flash('Deleted %s' % e)
        return redirect(url_for('cosmos.index'))

    @bprint.route('/')
    def index():
        executions = session.query(Execution).order_by(desc(Execution.created_on)).all()
        session.expire_all()
        return render_template('cosmos/index.html', executions=executions)

    @bprint.route('/')
    def home():
        return index()

    @bprint.route('/execution/<name>/')
    # @bprint.route('/execution/<int:id>/')
    def execution(name):
        execution = session.query(Execution).filter_by(name=name).one()
        return render_template('cosmos/execution.html', execution=execution)


    @bprint.route('/execution/<execution_name>/<stage_name>/')
    def stage(execution_name, stage_name):
        ex = session.query(Execution).filter_by(name=execution_name).one()
        stage = session.query(Stage).filter_by(execution_id=ex.id, name=stage_name).one()
        if stage is None:
            return abort(404)
        submitted = filter(lambda t: t.status == TaskStatus.submitted, stage.tasks)
        jm = JobManager(cosmos_app.get_submit_args)

        f = attrgetter('drm')
        drm_statuses = {}
        for drm, tasks in it.groupby(sorted(submitted, key=f), f):
            drm_statuses.update(jm.drms[drm].drm_statuses(list(tasks)))

        return render_template('cosmos/stage.html', stage=stage, drm_statuses=drm_statuses)
        # x=filter(lambda t: t.status == TaskStatus.submitted, stage.tasks))


    @bprint.route('/execution/<int:ex_id>/stage/<stage_name>/delete/')
    def stage_delete(ex_id, stage_name):
        s = session.query(Stage).filter(Stage.execution_id == ex_id, Stage.name == stage_name).one()
        flash('Deleted %s' % s)
        ex_url = s.execution.url
        s.delete(delete_files=False)
        return redirect(ex_url)

    # @bprint.route('/task/<int:id>/')
    # def task(id):
    # task = session.query(Task).get(id)
    # if task is None:
    #         return abort(404)
    #     return redirect(url_for('cosmos.task_friendly', ex_name=task.execution.name, stage_name=task.stage.name, task_id=task.id))

    # @bprint.route('/execution/<ex_name>/<stage_name>/task/')
    # def task(ex_name, stage_name):
    #     # resource_usage = [(category, field, getattr(task, field), profile_help[field]) for category, fields in
    #     #                   task.profile_fields for field in fields]
    #     assert request.method == 'GET'
    #     tags = request.args
    #     ex = session.query(Execution).filter_by(name=ex_name).one()
    #     stage = session.query(Stage).filter_by(execution=ex, name=stage_name).one()
    #     task = session.query(Task).filter_by(stage=stage, tags=tags).one()
    #     if task is None:
    #         return abort(404)
    #     resource_usage = [(field, getattr(task, field)) for field in task.profile_fields]
    #     return render_template('cosmos/task.html', task=task, resource_usage=resource_usage)

    @bprint.route('/execution/<ex_name>/<stage_name>/task/<task_id>')
    def task(ex_name, stage_name, task_id):
        # resource_usage = [(category, field, getattr(task, field), profile_help[field]) for category, fields in
        #                   task.profile_fields for field in fields]
        task = session.query(Task).get(task_id)
        if task is None:
            return abort(404)
        resource_usage = [(field, getattr(task, field)) for field in task.profile_fields]
        return render_template('cosmos/task.html', task=task, resource_usage=resource_usage)

    @bprint.route('/execution/<int:id>/taskgraph/<type>/')
    def taskgraph(id, type):
        from ..graph.draw import pygraphviz_available
        ex = get_execution(id)

        if pygraphviz_available:
            if type == 'task':
                svg = Markup(draw_task_graph(ex.task_graph()))
            else:
                svg = Markup(draw_stage_graph(ex.stage_graph(), url=True))
        else:
            svg = 'Pygraphviz not installed, cannot visualize'

        return render_template('cosmos/taskgraph.html', execution=ex, type=type,
                               svg=svg)

    # @bprint.route('/execution/<int:id>/taskgraph/svg/<type>/')
    # def taskgraph_svg(id, type, ):
    #     e = get_execution(id)
    #
    #     if type == 'task':
    #         return send_file(io.BytesIO(taskgraph_.tasks_to_image(e.tasks)), mimetype='image/svg+xml')
    #     else:
    #         return send_file(io.BytesIO(stages_to_image(e.stages)), mimetype='image/svg+xml')
    #
    return bprint


profile_help = dict(
    # time
    system_time='Amount of time that this process has been scheduled in kernel mode',
    user_time='Amount of time that this process has been scheduled in user mode.   This  includes  guest time,  guest_time  (time  spent  running a virtual CPU, see below), so that applications that are not aware of the guest time field do not lose that time from their calculations',
    cpu_time='system_time + user_time',
    wall_time='Elapsed real (wall clock) time used by the process.',
    percent_cpu='(cpu_time / wall_time) * 100',

    # memory
    avg_rss_mem='Average resident set size (Kb)',
    max_rss_mem='Maximum resident set size (Kb)',
    single_proc_max_peak_rss='Maximum single process rss used (Kb)',
    avg_virtual_mem='Average virtual memory used (Kb)',
    max_virtual_mem='Maximum virtual memory used (Kb)',
    single_proc_max_peak_virtual_mem='Maximum single process virtual memory used (Kb)',
    major_page_faults='The number of major faults the process has made which have required loading a memory page from disk',
    minor_page_faults='The number of minor faults the process has made which have not required loading a memory page from disk',
    avg_data_mem='Average size of data segments (Kb)',
    max_data_mem='Maximum size of data segments (Kb)',
    avg_lib_mem='Average library memory size (Kb)',
    max_lib_mem='Maximum library memory size (Kb)',
    avg_locked_mem='Average locked memory size (Kb)',
    max_locked_mem='Maximum locked memory size (Kb)',
    avg_num_threads='Average number of threads',
    max_num_threads='Maximum number of threads',
    avg_pte_mem='Average page table entries size (Kb)',
    max_pte_mem='Maximum page table entries size (Kb)',

    #io
    nonvoluntary_context_switches='Number of non voluntary context switches',
    voluntary_context_switches='Number of voluntary context switches',
    block_io_delays='Aggregated block I/O delays',
    avg_fdsize='Average number of file descriptor slots allocated',
    max_fdsize='Maximum number of file descriptor slots allocated',

    #misc
    num_polls='Number of times the resource usage statistics were polled from /proc',
    names='Names of all descendnt processes (there is always a python process for the profile_working.py script)',
    num_processes='Total number of descendant processes that were spawned',
    pids='Pids of all the descendant processes',
    exit_status='Exit status of the primary process being profiled',
    SC_CLK_TCK='sysconf(_SC_CLK_TCK), an operating system variable that is usually equal to 100, or centiseconds',
)

cosmos/web/templates/cosmos/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href=/cosmos/static/favicon.png">

    <title>{% block title %}Cosmos{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('cosmos.static', filename='bootstrap3/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('cosmos.static', filename='bootstrap3/datatables/assets/css/datatables.css') }}"
          rel="stylesheet">
    <link href="{{ url_for('cosmos.static', filename='custom.css') }}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>

<body>
{% block nav %}
<!-- Fixed navbar -->
<div class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="chain" data-target=".navbar-chain">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">{% block brand %}Cosmos{% endblock %}</a>
        </div>
        <div class="navbar-collapse collapse">
            <p class="navbar-text navbar-right">{% block navtext %}Workflow Management System{%endblock%}</p>
            {% block navmenu %}
            <ul class="nav navbar-nav">
                <li class="active"><a href="http://cosmos-workflow.rtfd.org/" target="_blank">Documentation</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Links <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">x</a></li>
                        <li class="divider"></li>
                        <li class="dropdown-header">name</li>
                        <li><a tabindex="-1" href="https://bitbucket.org"
                               target="_blank">BitBucket</a></li>
                    </ul>
                </li>
            </ul>
            {% endblock %}
        </div>
        <!--/.nav-chain -->
    </div>
</div>
{% endblock %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    {{ message }}
</div>
{% endfor %}

{% endif %}
<div class="col-md-12">
    {% block content %}

    {% endblock %}
</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="{{ url_for('cosmos.static', filename='bootstrap3/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('cosmos.static', filename='jquery.dataTables.min.js') }}"></script>
<script src="{{ url_for('cosmos.static', filename='datatables/assets/js/datatables.js') }}"></script>
<script type="text/javascript">
    function prependClass(sel, strClass) {
        var $el = jQuery(sel);

        /* prepend class */
        var classes = $el.attr('class');
        classes = strClass + ' ' + classes;
        $el.attr('class', classes);
    }


    $(document).ready(function () {
        $('.datatable').dataTable({
                                      "sPaginationType": "bs_normal",
                                      "bLengthChange": false,
                                      "iDisplayLength": 50,
                                      "aaSorting": []
                                  });
        $('.datatable').each(function () {
            var datatable = $(this);
            // SEARCH - Add the placeholder for Search and Turn this into in-line form control
            var search_input = datatable.closest('.dataTables_wrapper').find('div[id$=_filter] input');
            search_input.attr('placeholder', 'Search');
            search_input.addClass('form-control input-sm');
            // LENGTH - Inline-Form control
            var length_sel = datatable.closest('.dataTables_wrapper').find('div[id$=_length] select');
            length_sel.addClass('form-control input-sm');
            datatable.bind('page', function (e) {
                window.console && console.log('pagination event:', e) //this event must be fired whenever you paginate
            });

        });

        $('table tbody tr').hover(function () {
            prependClass(this, 'row_highlight');
        }, function () {
            $(this).removeClass('row_highlight');
        });
    });
</script>
{% block script %}
{% endblock %}
</body>
</html>

cosmos/web/templates/cosmos/execution.html
{% extends "cosmos/layout.html" %}

{% block title %}
{{ execution.name }}
{% endblock %}

{% block content %}

<ul class="breadcrumb">
    <li><a href="{{ url_for('.index') }}">Home</a></li>
    <li class="active">{{execution}}</li>
</ul>

<dl class="dl-horizontal">
    {% for k,v in execution.attrs_as_dict().items() %}
    <dt>{{k}}</dt>
    <dd>{{v}}</dd>
    {% endfor %}

    {% for k,v in execution.info.items() %}
    <dt>info.{{k}}</dt>
    <dd>{{v}}</dd>
    {% endfor %}

    <dt>output_dir</dt>
    <dd>{{execution.output_dir}}</dd>
    <dt>Visualize</dt>
    <dd>
        <a href="{{ url_for('.taskgraph', id=execution.id, type='recipe') }}">
            <button type="button" class="btn btn-info btn-sm">
                <span class="glyphicon glyphicon-eye-open"></span> StageGraph
            </button></a>
        <a href="{{ url_for('.taskgraph', id=execution.id, type='task') }}">
            <button type="button" class="btn btn-info btn-sm">
                <span class="glyphicon glyphicon-eye-open"></span> TaskGraph
            </button>
        </a>

    </dd>
</dl>


<div class="panel panel-primary">
    <div class="panel-heading">
        <span class="pull-right"></span>

        <h3 class="panel-title">{{execution}}.stages</h3>
    </div>
    <div class="panel-body">
        <table class="table table-condensed table-striped datatable" id="table_expected">
            <thead>
            <tr class="info">
                <th>#</th>
                <th>stage</th>
                <th>successful</th>
                <th>status</th>


                <th>tasks</th>
                <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                <th>failed</th>
                <th>avg(%_cpu)</th>
                <th>avg(cpu_req)</th>
                <th>avg(rss_mem)</th>
                <th>avg(mem_req)</th>
                <th>avg(wall_time)</th>
                <th>avg(cpu_time)</th>


                <th>action</th>
            </tr>
            </thead>
            <tbody>
            {% for s in execution.stages %}
            <tr>
                <td>{{s.number}}</td>
                <td><b><a href="{{ s.url  }}">{{ s.name }}</a></b></td>
                <td>{{s.successful|to_thumb}}</td>
                <td>{{ s.status }}</td>


                <td>{{ s.num_successful_tasks() }}/{{ s.tasks|length }}</td>
                <td>
                    {% with %}
                    {% set successful = s.percent_successful() %}
                    {% set running = s.percent_running() %}
                    {% set failed = s.percent_failed() %}
                    <div class="progress progress-striped">
                        <div class="progress-bar progress-bar-success progress-striped" style="width: {{successful}}%">
                            <span class="sr-only">{{successful}}% Complete (success)</span>
                        </div>
                        <div class="progress-bar progress-bar-warning progress-bar-striped" style="width: {{running}}%">
                            <span class="sr-only">{{running}}% Complete (running)</span>
                        </div>
                        <div class="progress-bar progress-bar-danger progress-striped" style="width: {{failed}}%">
                            <span class="sr-only">{{failed}}% Complete (failed)</span>
                        </div>
                    </div>
                    {%endwith%}
                </td>
                <td>{{ s.num_failed_tasks() }}</td>
                <td>{{s|stage_stat('percent_cpu', 'avg')}}</td>
                <td>{{s|stage_stat('cpu_req', 'avg')}}</td>
                <td>{{s|stage_stat('avg_rss_mem_kb', 'avg')}}</td>
                <td>{{s|stage_stat('mem_req', 'avg')}}</td>
                <td>{{s|stage_stat('wall_time', 'avg')}}</td>
                <td>{{s|stage_stat('cpu_time', 'avg')}}</td>

                <td>
                    <a href="{{ url_for('cosmos.stage_delete', ex_id=s.execution_id, stage_name=s.name) }}"
                       onclick="return confirm('This will delete all files associated with {{s}}.  Are you sure?')">
                        <button type="button" class="btn btn-danger btn-xs">
                            <span class="glyphicon glyphicon-remove"></span> delete
                        </button>
                    </a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
</div>


{% endblock %}

cosmos/web/templates/cosmos/index.html
{% extends "cosmos/layout.html" %}
{% block content %}

    <ul class="breadcrumb">
        <li><a href="{{ url_for('.index') }}">Home</a></li>
    </ul>


    <div class="panel panel-primary">
        <div class="panel-heading">
            <span class="pull-right"></span>

            <h3 class="panel-title">Executions</h3>
        </div>
        <div class="panel-body">

            <table class="table table-condensed table-striped datatable" id="table_expected">
                <thead>
                <tr>
                    <th>execution</th>
                    <th>successful</th>
                    <th>status</th>
                    <th>created_on</th>
                    <th>finished_on</th>
                    <th>wall time</th>
                    <th>testcases</th>
                    <th>action</th>
                </tr>
                </thead>
                <tbody>
                {% for e in executions %}
                    <tr>
                        <td><a href="{{ e.url }}">{{ e }}</a></td>
                        <td>{{e.successful|to_thumb}}</td>
                        <td>{{e.status}}</td>
                        <td>{{ e.created_on }}</td>
                        <td>{{ e.finished_on }}</td>
                        <td>{% if e.finished_on %}{{ e.finished_on - e.created_on|or_datetime_now }}{% endif %}</td>
                        <td>{{ e.info['testcases']|join(', ') }}</td>
                        <td>
                            <div class="btn-group btn-group-xs">
                                <button type="button" class="btn btn-default">
                                    <a href="{{ url_for('cosmos.execution_delete', id=e.id) }}"
                                       onclick="return confirm('This will delete all files associated with {{ e }}.  Are you sure?')">
                                        <span class="glyphicon glyphicon-remove"></span> delete
                                    </a></button>
                            </div>

                            <ul class="nav nav-pills">
                                <li>
                                    {% if e.info['type'] != 'Read Simulation' %}
                                    {% endif %}
                                </li>
                                <li>

                                </li>
                            </ul>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>


{% endblock %}

cosmos/web/templates/cosmos/layout.html
{% extends "cosmos/base.html" %}

cosmos/web/templates/cosmos/stage.html
{% extends "cosmos/layout.html" %}
{% block title %}
{{ stage.name }}
{% endblock %}
{% block content %}

<ul class="breadcrumb">
    <li><a href="{{ url_for('.index') }}">Home</a></li>
    <li><a href="{{ stage.execution.url }}">{{stage.execution}}</a></li>
    <li class="active">{{stage}}</li>
</ul>


<dl class="dl-horizontal" >
    {% for k,v in stage.attrs_as_dict().items() %}
    <dt>{{k}}</dt>
    <dd>{{v}}</dd>
    {% endfor %}
    <dt>parents</dt>
    <dd>{{stage.parents}}</dd>
</dl>
<dl class="dl-horizontal">
    {% with s=stage %}
    <dt>progress</dt>
    <dd>{{ s.num_successful_tasks() }}/{{ s.tasks|length }}</dd>
    <dt>&nbsp;</dt>
    <dd>
        {% with %}
        {% set successful = s.percent_successful() %}
        {% set running = s.percent_running() %}
        {% set failed = s.percent_failed() %}
        <div class="progress progress-striped" style="width: 150px">
            <div class="progress-bar progress-bar-success progress-striped" style="width: {{successful}}%">
                <span class="sr-only">{{successful}}% Complete (success)</span>
            </div>
            <div class="progress-bar progress-bar-warning progress-bar-striped" style="width: {{running}}%">
                <span class="sr-only">{{running}}% Complete (running)</span>
            </div>
            <div class="progress-bar progress-bar-danger progress-striped" style="width: {{failed}}%">
                <span class="sr-only">{{failed}}% Complete (failed)</span>
            </div>
        </div>
        {%endwith%}
    </dd>
    <dt>failed</dt>
    <dd>{{ s.num_failed_tasks() }}</dd>
    <dt>avg(%_cpu)</dt>
    <dd>{{s|stage_stat('percent_cpu', 'avg')}}</dd>
    <dt>avg(cpu_req)</dt>
    <dd>{{s|stage_stat('cpu_req', 'avg')}}</dd>
    <dt>avg(rss_mem)</dt>
    <dd>{{s|stage_stat('avg_rss_mem_kb', 'avg')}}</dd>
    <dt>avg(mem_req)</dt>
    <dd>{{s|stage_stat('mem_req', 'avg')}}</dd>
    <dt>avg(wall_time)</dt>
    <dd>{{s|stage_stat('wall_time', 'avg')}}</dd>
    <dt>avg(cpu_time)</dt>
    <dd>{{s|stage_stat('cpu_time', 'avg')}}</dd>
    {%endwith%}
</dl>
<div style="clear:both">
</div>
<div class="panel panel-primary">
    <div class="panel-heading">
        <span class="pull-right"></span>

        <h3 class="panel-title">{{stage}}.tasks</h3>
    </div>
    <div class="panel-body">
        <table class="table table-condensed table-striped datatable" id="table_expected">
            <thead>
            <tr>
                <th>id</th>
                <th>task</th>
                <th>successful</th>
                <th>status</th>
                <th>drm_status</th>
                <th>drm_jobid</th>
                <th>attempts</th>
                <th>submitted_on</th>
                <th>finished_on</th>
                <th>wall_time</th>
            </tr>
            </thead>
            <tbody>
            {% for t in stage.tasks %}
            <tr>
                <td>{{t.id}}</td>
                <td><a href="{{ t.url }}">{{t.tags}}</a></td>
                <td>{{t.successful|to_thumb}}</td>
                <td>{{t.status}}</td>
                <td>{{drm_statuses.get(t.drm_jobID,'')}}</td>
                <th>{{t.drm_jobID}}</th>
                <td>{{t.attempt}}</td>
                <td>{{t.submitted_on}}</td>
                <td>{{t.finished_on}}</td>
                <td>{% if t.finished_on %}{{ t.finished_on - t.started_on|or_datetime_now }}{% endif %}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
</div>


{% endblock %}

cosmos/web/templates/cosmos/task.html
{% extends "cosmos/layout.html" %}
{% block title %}
    {{ task }}
{% endblock %}

{% macro long_list(items) -%}
    <ul>
        {% if items|length >5 %}
            {% for p in items[:4] %}
                <li><a href="{{ p.url }}">{{ p }}</a></li>
            {% endfor %}
            <li>({{ items|length }} total)...</li>
        {% else %}
            {% for p in items %}
                <a href="{{ p.url }}">{{ p }}</a><br/>
            {% endfor %}
        {% endif %}
    </ul>
{%- endmacro %}


{% block content %}
    <ul class="breadcrumb">
        <li><a href="{{ url_for('.index') }}">Home</a></li>
        <li><a href="{{ task.execution.url }}">{{ task.execution }}</a></li>
        <li><a href="{{ task.stage.url }}">{{ task.stage }}</a></li>
        <li class="active">{{ task }}</li>
    </ul>
    <div class="row">
        <div class="col-md-6">
            <h3>Task Info</h3>
            <dl class="dl-horizontal">
                {% for k,v in task.attrs_as_dict().items() %}
                    {% if k != 'tags' %}
                        <dt>{{ k }}</dt>
                        <dd>{{ v or None }}</dd>
                    {% endif %}
                {% endfor %}


                {% for tf in task.input_files %}
                    <dt>input file</dt>
                    <dd>{{ tf }}</dd>
                {% endfor %}
                {% for tf in task.output_files %}
                    <dt>output file</dt>
                    <dd>{{ tf }}</dd>
                {% endfor %}
            </dl>
        </div>
        <h3>Task Tags</h3>

        <div class="col-md-6">
            <dl class="dl-horizontal">
                {% for k,v in task.tags.items() %}
                    <dt>{{ k }}</dt>
                    <dd>{{ v }}</dd>
                {% endfor %}
            </dl>
        </div>
    </div>
    <div class="row">
        <dl class="dl-horizontal">
            <dt>parents</dt>
            <dd>
                {{ long_list(task.parents) }}
            </dd>
            <dt>children</dt>
            <dd>
                {{ long_list(task.children) }}
            </dd>
        </dl>
    </div>

    <div class="panel panel-primary">
        <div class="panel-heading">
            <span class="pull-right">{{ task.output_command_script_path }}</span>

            <h3 class="panel-title">Command</h3>
        </div>
        <div class="panel-body">
            <pre>{{ task.command_script_text }}</pre>
        </div>
    </div>

    <div class="panel panel-info">
        <div class="panel-heading">
            <span class="pull-right">{{ task.output_stdout_path }}</span>

            <h3 class="panel-title">STDOUT</h3>
        </div>
        <div class="panel-body">
            <pre>{{ task.stdout_text }}</pre>
        </div>
    </div>

    <div class="panel panel-danger">
        <div class="panel-heading">
            <span class="pull-right">{{ task.output_stderr_path }}</span>

            <h3 class="panel-title">STDERR </h3>
        </div>
        <div class="panel-body">
            <pre>{{ task.stderr_text }}</pre>

        </div>
    </div>

    <h2>Resources</h2>
    <table class="table table-striped table-condensed">
        <tbody>
        <tr>
            <th>Name</th>
            <th>Value</th>
        </tbody>
        {% for field, value in resource_usage %}
            <tr>
                <td>{{ field| replace('_kb','') }}</td>
                <td>{{ field|format_resource_usage(value) }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

cosmos/web/templates/cosmos/taskgraph.html
{% extends "cosmos/layout.html" %}

{% block content %}
<ul class="breadcrumb">
    <li><a href="{{ url_for('.index') }}">Home</a></li>
    <li><a href="{{ execution.url }}">{{execution}}</a></li>
    <li class="active">taskgraph</li>
</ul>
<p>
{% if type == 'task' %}
    <a href="{{ url_for('.taskgraph', id=execution.id, type='recipe') }}">
        <button type="button" class="btn btn-primary btn-sm">
            <span class="glyphicon glyphicon-eye-open"></span> StageGraph
        </button>
    </a>
{% else %}
    <a href="{{ url_for('.taskgraph', id=execution.id, type='task') }}">
        <button type="button" class="btn btn-primary btn-sm">
            <span class="glyphicon glyphicon-eye-open"></span> TaskGraph
        </button>
    </a>
{% endif %}
</p>
        {{svg}}

{#
    <div class="center-block">
        <object type="image/svg+xml" data="{{ url_for('.taskgraph_svg', id=execution.id, type=type) }}"></object>
    </div>
#}

{% endblock %}